// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfsService.proto

#include "nfsService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace nfsService {
class GetClientIdsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetClientIdsRequest> _instance;
} _GetClientIdsRequest_default_instance_;
class GetClientIdsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetClientIdsResponse> _instance;
} _GetClientIdsResponse_default_instance_;
class GetNfsGraceRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetNfsGraceRequest> _instance;
} _GetNfsGraceRequest_default_instance_;
class GetNfsGraceResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetNfsGraceResponse> _instance;
} _GetNfsGraceResponse_default_instance_;
class GraceWithEventDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GraceWithEvent> _instance;
} _GraceWithEvent_default_instance_;
class GraceStatusDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GraceStatus> _instance;
} _GraceStatus_default_instance_;
class GetSessionIdsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetSessionIdsRequest> _instance;
} _GetSessionIdsRequest_default_instance_;
class GetSessionIdsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetSessionIdsResponse> _instance;
} _GetSessionIdsResponse_default_instance_;
}  // namespace nfsService
static void InitDefaultsscc_info_GetClientIdsRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetClientIdsRequest_default_instance_;
    new (ptr) ::nfsService::GetClientIdsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetClientIdsRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetClientIdsRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetClientIdsResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetClientIdsResponse_default_instance_;
    new (ptr) ::nfsService::GetClientIdsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetClientIdsResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetClientIdsResponse_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetNfsGraceRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetNfsGraceRequest_default_instance_;
    new (ptr) ::nfsService::GetNfsGraceRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetNfsGraceRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetNfsGraceRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetNfsGraceResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetNfsGraceResponse_default_instance_;
    new (ptr) ::nfsService::GetNfsGraceResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetNfsGraceResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetNfsGraceResponse_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetSessionIdsRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetSessionIdsRequest_default_instance_;
    new (ptr) ::nfsService::GetSessionIdsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetSessionIdsRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetSessionIdsRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetSessionIdsResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetSessionIdsResponse_default_instance_;
    new (ptr) ::nfsService::GetSessionIdsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetSessionIdsResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetSessionIdsResponse_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GraceStatus_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GraceStatus_default_instance_;
    new (ptr) ::nfsService::GraceStatus();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GraceStatus_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GraceStatus_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GraceWithEvent_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GraceWithEvent_default_instance_;
    new (ptr) ::nfsService::GraceWithEvent();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GraceWithEvent_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GraceWithEvent_nfsService_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_nfsService_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_nfsService_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_nfsService_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_nfsService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsResponse, client_ids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceResponse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceResponse, ingrace_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceWithEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceWithEvent, event_),
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceWithEvent, nodeid_),
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceWithEvent, ipaddr_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceStatus, gracestarted_),
  PROTOBUF_FIELD_OFFSET(::nfsService::GraceStatus, response_msg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsResponse, session_ids_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::nfsService::GetClientIdsRequest)},
  { 5, -1, sizeof(::nfsService::GetClientIdsResponse)},
  { 11, -1, sizeof(::nfsService::GetNfsGraceRequest)},
  { 16, 22, sizeof(::nfsService::GetNfsGraceResponse)},
  { 23, -1, sizeof(::nfsService::GraceWithEvent)},
  { 31, -1, sizeof(::nfsService::GraceStatus)},
  { 38, -1, sizeof(::nfsService::GetSessionIdsRequest)},
  { 43, -1, sizeof(::nfsService::GetSessionIdsResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetClientIdsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetClientIdsResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetNfsGraceRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetNfsGraceResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GraceWithEvent_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GraceStatus_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetSessionIdsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetSessionIdsResponse_default_instance_),
};

const char descriptor_table_protodef_nfsService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020nfsService.proto\022\nnfsService\"\025\n\023GetCli"
  "entIdsRequest\"*\n\024GetClientIdsResponse\022\022\n"
  "\nclient_ids\030\001 \003(\004\"\024\n\022GetNfsGraceRequest\""
  "7\n\023GetNfsGraceResponse\022\024\n\007ingrace\030\001 \001(\010H"
  "\000\210\001\001B\n\n\010_ingrace\"\?\n\016GraceWithEvent\022\r\n\005Ev"
  "ent\030\001 \001(\005\022\016\n\006NodeId\030\002 \001(\005\022\016\n\006IpAddr\030\003 \001("
  "\t\"9\n\013GraceStatus\022\024\n\014graceStarted\030\001 \001(\010\022\024"
  "\n\014response_msg\030\002 \001(\t\"\026\n\024GetSessionIdsReq"
  "uest\",\n\025GetSessionIdsResponse\022\023\n\013session"
  "_ids\030\001 \003(\t2`\n\013GetClientId\022Q\n\014GetClientId"
  "s\022\037.nfsService.GetClientIdsRequest\032 .nfs"
  "Service.GetClientIdsResponse2`\n\013GetNfsGr"
  "ace\022Q\n\016GetGracePeriod\022\036.nfsService.GetNf"
  "sGraceRequest\032\037.nfsService.GetNfsGraceRe"
  "sponse2[\n\rStartNfsGrace\022J\n\023StartGraceWit"
  "hEvent\022\032.nfsService.GraceWithEvent\032\027.nfs"
  "Service.GraceStatus2d\n\014GetSessionId\022T\n\rG"
  "etSessionIds\022 .nfsService.GetSessionIdsR"
  "equest\032!.nfsService.GetSessionIdsRespons"
  "eb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_nfsService_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_nfsService_2eproto_sccs[8] = {
  &scc_info_GetClientIdsRequest_nfsService_2eproto.base,
  &scc_info_GetClientIdsResponse_nfsService_2eproto.base,
  &scc_info_GetNfsGraceRequest_nfsService_2eproto.base,
  &scc_info_GetNfsGraceResponse_nfsService_2eproto.base,
  &scc_info_GetSessionIdsRequest_nfsService_2eproto.base,
  &scc_info_GetSessionIdsResponse_nfsService_2eproto.base,
  &scc_info_GraceStatus_nfsService_2eproto.base,
  &scc_info_GraceWithEvent_nfsService_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_nfsService_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nfsService_2eproto = {
  false, false, descriptor_table_protodef_nfsService_2eproto, "nfsService.proto", 769,
  &descriptor_table_nfsService_2eproto_once, descriptor_table_nfsService_2eproto_sccs, descriptor_table_nfsService_2eproto_deps, 8, 0,
  schemas, file_default_instances, TableStruct_nfsService_2eproto::offsets,
  file_level_metadata_nfsService_2eproto, 8, file_level_enum_descriptors_nfsService_2eproto, file_level_service_descriptors_nfsService_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_nfsService_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_nfsService_2eproto)), true);
namespace nfsService {

// ===================================================================

class GetClientIdsRequest::_Internal {
 public:
};

GetClientIdsRequest::GetClientIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetClientIdsRequest)
}
GetClientIdsRequest::GetClientIdsRequest(const GetClientIdsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetClientIdsRequest)
}

void GetClientIdsRequest::SharedCtor() {
}

GetClientIdsRequest::~GetClientIdsRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetClientIdsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetClientIdsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetClientIdsRequest::ArenaDtor(void* object) {
  GetClientIdsRequest* _this = reinterpret_cast< GetClientIdsRequest* >(object);
  (void)_this;
}
void GetClientIdsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetClientIdsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetClientIdsRequest& GetClientIdsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetClientIdsRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetClientIdsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetClientIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetClientIdsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetClientIdsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetClientIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetClientIdsRequest)
  return target;
}

size_t GetClientIdsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetClientIdsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetClientIdsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetClientIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetClientIdsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetClientIdsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetClientIdsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetClientIdsRequest)
    MergeFrom(*source);
  }
}

void GetClientIdsRequest::MergeFrom(const GetClientIdsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetClientIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetClientIdsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetClientIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetClientIdsRequest::CopyFrom(const GetClientIdsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetClientIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetClientIdsRequest::IsInitialized() const {
  return true;
}

void GetClientIdsRequest::InternalSwap(GetClientIdsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetClientIdsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetClientIdsResponse::_Internal {
 public:
};

GetClientIdsResponse::GetClientIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  client_ids_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetClientIdsResponse)
}
GetClientIdsResponse::GetClientIdsResponse(const GetClientIdsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      client_ids_(from.client_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetClientIdsResponse)
}

void GetClientIdsResponse::SharedCtor() {
}

GetClientIdsResponse::~GetClientIdsResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetClientIdsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetClientIdsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetClientIdsResponse::ArenaDtor(void* object) {
  GetClientIdsResponse* _this = reinterpret_cast< GetClientIdsResponse* >(object);
  (void)_this;
}
void GetClientIdsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetClientIdsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetClientIdsResponse& GetClientIdsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetClientIdsResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetClientIdsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetClientIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  client_ids_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetClientIdsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated uint64 client_ids = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_client_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8) {
          _internal_add_client_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetClientIdsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetClientIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint64 client_ids = 1;
  {
    int byte_size = _client_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          1, _internal_client_ids(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetClientIdsResponse)
  return target;
}

size_t GetClientIdsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetClientIdsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 client_ids = 1;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt64Size(this->client_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _client_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetClientIdsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetClientIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetClientIdsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetClientIdsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetClientIdsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetClientIdsResponse)
    MergeFrom(*source);
  }
}

void GetClientIdsResponse::MergeFrom(const GetClientIdsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetClientIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  client_ids_.MergeFrom(from.client_ids_);
}

void GetClientIdsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetClientIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetClientIdsResponse::CopyFrom(const GetClientIdsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetClientIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetClientIdsResponse::IsInitialized() const {
  return true;
}

void GetClientIdsResponse::InternalSwap(GetClientIdsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  client_ids_.InternalSwap(&other->client_ids_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetClientIdsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetNfsGraceRequest::_Internal {
 public:
};

GetNfsGraceRequest::GetNfsGraceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetNfsGraceRequest)
}
GetNfsGraceRequest::GetNfsGraceRequest(const GetNfsGraceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetNfsGraceRequest)
}

void GetNfsGraceRequest::SharedCtor() {
}

GetNfsGraceRequest::~GetNfsGraceRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetNfsGraceRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetNfsGraceRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetNfsGraceRequest::ArenaDtor(void* object) {
  GetNfsGraceRequest* _this = reinterpret_cast< GetNfsGraceRequest* >(object);
  (void)_this;
}
void GetNfsGraceRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetNfsGraceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetNfsGraceRequest& GetNfsGraceRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetNfsGraceRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetNfsGraceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetNfsGraceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNfsGraceRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetNfsGraceRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetNfsGraceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetNfsGraceRequest)
  return target;
}

size_t GetNfsGraceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetNfsGraceRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetNfsGraceRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetNfsGraceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetNfsGraceRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetNfsGraceRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetNfsGraceRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetNfsGraceRequest)
    MergeFrom(*source);
  }
}

void GetNfsGraceRequest::MergeFrom(const GetNfsGraceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetNfsGraceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetNfsGraceRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetNfsGraceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetNfsGraceRequest::CopyFrom(const GetNfsGraceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetNfsGraceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNfsGraceRequest::IsInitialized() const {
  return true;
}

void GetNfsGraceRequest::InternalSwap(GetNfsGraceRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNfsGraceRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetNfsGraceResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<GetNfsGraceResponse>()._has_bits_);
  static void set_has_ingrace(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

GetNfsGraceResponse::GetNfsGraceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetNfsGraceResponse)
}
GetNfsGraceResponse::GetNfsGraceResponse(const GetNfsGraceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ingrace_ = from.ingrace_;
  // @@protoc_insertion_point(copy_constructor:nfsService.GetNfsGraceResponse)
}

void GetNfsGraceResponse::SharedCtor() {
  ingrace_ = false;
}

GetNfsGraceResponse::~GetNfsGraceResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetNfsGraceResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetNfsGraceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetNfsGraceResponse::ArenaDtor(void* object) {
  GetNfsGraceResponse* _this = reinterpret_cast< GetNfsGraceResponse* >(object);
  (void)_this;
}
void GetNfsGraceResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetNfsGraceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetNfsGraceResponse& GetNfsGraceResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetNfsGraceResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetNfsGraceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetNfsGraceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ingrace_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNfsGraceResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool ingrace = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_ingrace(&has_bits);
          ingrace_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetNfsGraceResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetNfsGraceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ingrace = 1;
  if (_internal_has_ingrace()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_ingrace(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetNfsGraceResponse)
  return target;
}

size_t GetNfsGraceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetNfsGraceResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ingrace = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetNfsGraceResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetNfsGraceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetNfsGraceResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetNfsGraceResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetNfsGraceResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetNfsGraceResponse)
    MergeFrom(*source);
  }
}

void GetNfsGraceResponse::MergeFrom(const GetNfsGraceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetNfsGraceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_ingrace()) {
    _internal_set_ingrace(from._internal_ingrace());
  }
}

void GetNfsGraceResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetNfsGraceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetNfsGraceResponse::CopyFrom(const GetNfsGraceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetNfsGraceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNfsGraceResponse::IsInitialized() const {
  return true;
}

void GetNfsGraceResponse::InternalSwap(GetNfsGraceResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(ingrace_, other->ingrace_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNfsGraceResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GraceWithEvent::_Internal {
 public:
};

GraceWithEvent::GraceWithEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GraceWithEvent)
}
GraceWithEvent::GraceWithEvent(const GraceWithEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ipaddr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ipaddr().empty()) {
    ipaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_ipaddr(), 
      GetArena());
  }
  ::memcpy(&event_, &from.event_,
    static_cast<size_t>(reinterpret_cast<char*>(&nodeid_) -
    reinterpret_cast<char*>(&event_)) + sizeof(nodeid_));
  // @@protoc_insertion_point(copy_constructor:nfsService.GraceWithEvent)
}

void GraceWithEvent::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GraceWithEvent_nfsService_2eproto.base);
  ipaddr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&event_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&nodeid_) -
      reinterpret_cast<char*>(&event_)) + sizeof(nodeid_));
}

GraceWithEvent::~GraceWithEvent() {
  // @@protoc_insertion_point(destructor:nfsService.GraceWithEvent)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GraceWithEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ipaddr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GraceWithEvent::ArenaDtor(void* object) {
  GraceWithEvent* _this = reinterpret_cast< GraceWithEvent* >(object);
  (void)_this;
}
void GraceWithEvent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GraceWithEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GraceWithEvent& GraceWithEvent::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GraceWithEvent_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GraceWithEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GraceWithEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ipaddr_.ClearToEmpty();
  ::memset(&event_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nodeid_) -
      reinterpret_cast<char*>(&event_)) + sizeof(nodeid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GraceWithEvent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 Event = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          event_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 NodeId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          nodeid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string IpAddr = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_ipaddr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "nfsService.GraceWithEvent.IpAddr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GraceWithEvent::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GraceWithEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 Event = 1;
  if (this->event() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_event(), target);
  }

  // int32 NodeId = 2;
  if (this->nodeid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_nodeid(), target);
  }

  // string IpAddr = 3;
  if (this->ipaddr().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ipaddr().data(), static_cast<int>(this->_internal_ipaddr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nfsService.GraceWithEvent.IpAddr");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_ipaddr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GraceWithEvent)
  return target;
}

size_t GraceWithEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GraceWithEvent)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string IpAddr = 3;
  if (this->ipaddr().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ipaddr());
  }

  // int32 Event = 1;
  if (this->event() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_event());
  }

  // int32 NodeId = 2;
  if (this->nodeid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nodeid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GraceWithEvent::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GraceWithEvent)
  GOOGLE_DCHECK_NE(&from, this);
  const GraceWithEvent* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GraceWithEvent>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GraceWithEvent)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GraceWithEvent)
    MergeFrom(*source);
  }
}

void GraceWithEvent::MergeFrom(const GraceWithEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GraceWithEvent)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ipaddr().size() > 0) {
    _internal_set_ipaddr(from._internal_ipaddr());
  }
  if (from.event() != 0) {
    _internal_set_event(from._internal_event());
  }
  if (from.nodeid() != 0) {
    _internal_set_nodeid(from._internal_nodeid());
  }
}

void GraceWithEvent::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GraceWithEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraceWithEvent::CopyFrom(const GraceWithEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GraceWithEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraceWithEvent::IsInitialized() const {
  return true;
}

void GraceWithEvent::InternalSwap(GraceWithEvent* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ipaddr_.Swap(&other->ipaddr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GraceWithEvent, nodeid_)
      + sizeof(GraceWithEvent::nodeid_)
      - PROTOBUF_FIELD_OFFSET(GraceWithEvent, event_)>(
          reinterpret_cast<char*>(&event_),
          reinterpret_cast<char*>(&other->event_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GraceWithEvent::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GraceStatus::_Internal {
 public:
};

GraceStatus::GraceStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GraceStatus)
}
GraceStatus::GraceStatus(const GraceStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  response_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_response_msg().empty()) {
    response_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_response_msg(), 
      GetArena());
  }
  gracestarted_ = from.gracestarted_;
  // @@protoc_insertion_point(copy_constructor:nfsService.GraceStatus)
}

void GraceStatus::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GraceStatus_nfsService_2eproto.base);
  response_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gracestarted_ = false;
}

GraceStatus::~GraceStatus() {
  // @@protoc_insertion_point(destructor:nfsService.GraceStatus)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GraceStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  response_msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GraceStatus::ArenaDtor(void* object) {
  GraceStatus* _this = reinterpret_cast< GraceStatus* >(object);
  (void)_this;
}
void GraceStatus::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GraceStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GraceStatus& GraceStatus::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GraceStatus_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GraceStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GraceStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  response_msg_.ClearToEmpty();
  gracestarted_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GraceStatus::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool graceStarted = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          gracestarted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string response_msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_response_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "nfsService.GraceStatus.response_msg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GraceStatus::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GraceStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool graceStarted = 1;
  if (this->gracestarted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_gracestarted(), target);
  }

  // string response_msg = 2;
  if (this->response_msg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_response_msg().data(), static_cast<int>(this->_internal_response_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nfsService.GraceStatus.response_msg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_response_msg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GraceStatus)
  return target;
}

size_t GraceStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GraceStatus)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string response_msg = 2;
  if (this->response_msg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_response_msg());
  }

  // bool graceStarted = 1;
  if (this->gracestarted() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GraceStatus::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GraceStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const GraceStatus* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GraceStatus>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GraceStatus)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GraceStatus)
    MergeFrom(*source);
  }
}

void GraceStatus::MergeFrom(const GraceStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GraceStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.response_msg().size() > 0) {
    _internal_set_response_msg(from._internal_response_msg());
  }
  if (from.gracestarted() != 0) {
    _internal_set_gracestarted(from._internal_gracestarted());
  }
}

void GraceStatus::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GraceStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraceStatus::CopyFrom(const GraceStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GraceStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraceStatus::IsInitialized() const {
  return true;
}

void GraceStatus::InternalSwap(GraceStatus* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  response_msg_.Swap(&other->response_msg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(gracestarted_, other->gracestarted_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GraceStatus::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetSessionIdsRequest::_Internal {
 public:
};

GetSessionIdsRequest::GetSessionIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetSessionIdsRequest)
}
GetSessionIdsRequest::GetSessionIdsRequest(const GetSessionIdsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetSessionIdsRequest)
}

void GetSessionIdsRequest::SharedCtor() {
}

GetSessionIdsRequest::~GetSessionIdsRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetSessionIdsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetSessionIdsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetSessionIdsRequest::ArenaDtor(void* object) {
  GetSessionIdsRequest* _this = reinterpret_cast< GetSessionIdsRequest* >(object);
  (void)_this;
}
void GetSessionIdsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetSessionIdsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetSessionIdsRequest& GetSessionIdsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetSessionIdsRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetSessionIdsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetSessionIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetSessionIdsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetSessionIdsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetSessionIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetSessionIdsRequest)
  return target;
}

size_t GetSessionIdsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetSessionIdsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetSessionIdsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetSessionIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSessionIdsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetSessionIdsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetSessionIdsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetSessionIdsRequest)
    MergeFrom(*source);
  }
}

void GetSessionIdsRequest::MergeFrom(const GetSessionIdsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetSessionIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetSessionIdsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetSessionIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSessionIdsRequest::CopyFrom(const GetSessionIdsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetSessionIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSessionIdsRequest::IsInitialized() const {
  return true;
}

void GetSessionIdsRequest::InternalSwap(GetSessionIdsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetSessionIdsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetSessionIdsResponse::_Internal {
 public:
};

GetSessionIdsResponse::GetSessionIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  session_ids_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetSessionIdsResponse)
}
GetSessionIdsResponse::GetSessionIdsResponse(const GetSessionIdsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      session_ids_(from.session_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetSessionIdsResponse)
}

void GetSessionIdsResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GetSessionIdsResponse_nfsService_2eproto.base);
}

GetSessionIdsResponse::~GetSessionIdsResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetSessionIdsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetSessionIdsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetSessionIdsResponse::ArenaDtor(void* object) {
  GetSessionIdsResponse* _this = reinterpret_cast< GetSessionIdsResponse* >(object);
  (void)_this;
}
void GetSessionIdsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetSessionIdsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetSessionIdsResponse& GetSessionIdsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetSessionIdsResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetSessionIdsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetSessionIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  session_ids_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetSessionIdsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string session_ids = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_session_ids();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "nfsService.GetSessionIdsResponse.session_ids"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetSessionIdsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetSessionIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string session_ids = 1;
  for (int i = 0, n = this->_internal_session_ids_size(); i < n; i++) {
    const auto& s = this->_internal_session_ids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nfsService.GetSessionIdsResponse.session_ids");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetSessionIdsResponse)
  return target;
}

size_t GetSessionIdsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetSessionIdsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string session_ids = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(session_ids_.size());
  for (int i = 0, n = session_ids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      session_ids_.Get(i));
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetSessionIdsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetSessionIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSessionIdsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetSessionIdsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetSessionIdsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetSessionIdsResponse)
    MergeFrom(*source);
  }
}

void GetSessionIdsResponse::MergeFrom(const GetSessionIdsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetSessionIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  session_ids_.MergeFrom(from.session_ids_);
}

void GetSessionIdsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetSessionIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSessionIdsResponse::CopyFrom(const GetSessionIdsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetSessionIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSessionIdsResponse::IsInitialized() const {
  return true;
}

void GetSessionIdsResponse::InternalSwap(GetSessionIdsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  session_ids_.InternalSwap(&other->session_ids_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetSessionIdsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace nfsService
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::nfsService::GetClientIdsRequest* Arena::CreateMaybeMessage< ::nfsService::GetClientIdsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetClientIdsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetClientIdsResponse* Arena::CreateMaybeMessage< ::nfsService::GetClientIdsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetClientIdsResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetNfsGraceRequest* Arena::CreateMaybeMessage< ::nfsService::GetNfsGraceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetNfsGraceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetNfsGraceResponse* Arena::CreateMaybeMessage< ::nfsService::GetNfsGraceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetNfsGraceResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GraceWithEvent* Arena::CreateMaybeMessage< ::nfsService::GraceWithEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GraceWithEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GraceStatus* Arena::CreateMaybeMessage< ::nfsService::GraceStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GraceStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetSessionIdsRequest* Arena::CreateMaybeMessage< ::nfsService::GetSessionIdsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetSessionIdsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetSessionIdsResponse* Arena::CreateMaybeMessage< ::nfsService::GetSessionIdsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetSessionIdsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
