// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nfsService.proto
// Original file comments:
// Copyright (C) 2025, The Linux Box Corporation
// Contributor : Avani Rateria <arateria@redhat.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
//
// -------------
//
#ifndef GRPC_nfsService_2eproto__INCLUDED
#define GRPC_nfsService_2eproto__INCLUDED

#include "nfsService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace nfsService {

// Get the connected client ids
class GetClientId final {
 public:
  static constexpr char const* service_full_name() {
    return "nfsService.GetClientId";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::nfsService::GetClientIdsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>> AsyncGetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>>(AsyncGetClientIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>> PrepareAsyncGetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>>(PrepareAsyncGetClientIdsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>* AsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetClientIdsResponse>* PrepareAsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::nfsService::GetClientIdsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>> AsyncGetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>>(AsyncGetClientIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>> PrepareAsyncGetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>>(PrepareAsyncGetClientIdsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>* AsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>* PrepareAsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetClientIds_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetClientIds(::grpc::ServerContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetClientIds() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClientIds(::grpc::ServerContext* context, ::nfsService::GetClientIdsRequest* request, ::grpc::ServerAsyncResponseWriter< ::nfsService::GetClientIdsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetClientIds<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetClientIds() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response) { return this->GetClientIds(context, request, response); }));}
    void SetMessageAllocatorFor_GetClientIds(
        ::grpc::MessageAllocator< ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClientIds(
      ::grpc::CallbackServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetClientIds<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetClientIds() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetClientIds() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClientIds(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetClientIds() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetClientIds(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClientIds(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetClientIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetClientIds() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse>* streamer) {
                       return this->StreamedGetClientIds(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetClientIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetClientIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetClientIdsRequest* /*request*/, ::nfsService::GetClientIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetClientIds(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nfsService::GetClientIdsRequest,::nfsService::GetClientIdsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetClientIds<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetClientIds<Service > StreamedService;
};

// Grace related requests
//
// Get if nfs in grace
class GetNfsGrace final {
 public:
  static constexpr char const* service_full_name() {
    return "nfsService.GetNfsGrace";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::nfsService::GetNfsGraceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>> AsyncGetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>>(AsyncGetGracePeriodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>> PrepareAsyncGetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>>(PrepareAsyncGetGracePeriodRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>* AsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetNfsGraceResponse>* PrepareAsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::nfsService::GetNfsGraceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>> AsyncGetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>>(AsyncGetGracePeriodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>> PrepareAsyncGetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>>(PrepareAsyncGetGracePeriodRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, std::function<void(::grpc::Status)>) override;
      void GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>* AsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>* PrepareAsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetGracePeriod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetGracePeriod(::grpc::ServerContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetGracePeriod(::grpc::ServerContext* context, ::nfsService::GetNfsGraceRequest* request, ::grpc::ServerAsyncResponseWriter< ::nfsService::GetNfsGraceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetGracePeriod<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response) { return this->GetGracePeriod(context, request, response); }));}
    void SetMessageAllocatorFor_GetGracePeriod(
        ::grpc::MessageAllocator< ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetGracePeriod(
      ::grpc::CallbackServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetGracePeriod<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetGracePeriod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetGracePeriod(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetGracePeriod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetGracePeriod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetGracePeriod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse>* streamer) {
                       return this->StreamedGetGracePeriod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetGracePeriod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetGracePeriod(::grpc::ServerContext* /*context*/, const ::nfsService::GetNfsGraceRequest* /*request*/, ::nfsService::GetNfsGraceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetGracePeriod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nfsService::GetNfsGraceRequest,::nfsService::GetNfsGraceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetGracePeriod<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetGracePeriod<Service > StreamedService;
};

// Invoke grace period on the NFS Ganesha
class StartNfsGrace final {
 public:
  static constexpr char const* service_full_name() {
    return "nfsService.StartNfsGrace";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::nfsService::GraceStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>> AsyncStartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>>(AsyncStartGraceWithEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>> PrepareAsyncStartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>>(PrepareAsyncStartGraceWithEventRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>* AsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GraceStatus>* PrepareAsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::nfsService::GraceStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>> AsyncStartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>>(AsyncStartGraceWithEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>> PrepareAsyncStartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>>(PrepareAsyncStartGraceWithEventRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, std::function<void(::grpc::Status)>) override;
      void StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>* AsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>* PrepareAsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartGraceWithEvent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartGraceWithEvent(::grpc::ServerContext* context, ::nfsService::GraceWithEvent* request, ::grpc::ServerAsyncResponseWriter< ::nfsService::GraceStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartGraceWithEvent<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nfsService::GraceWithEvent, ::nfsService::GraceStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response) { return this->StartGraceWithEvent(context, request, response); }));}
    void SetMessageAllocatorFor_StartGraceWithEvent(
        ::grpc::MessageAllocator< ::nfsService::GraceWithEvent, ::nfsService::GraceStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nfsService::GraceWithEvent, ::nfsService::GraceStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartGraceWithEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StartGraceWithEvent<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartGraceWithEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartGraceWithEvent(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartGraceWithEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartGraceWithEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartGraceWithEvent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nfsService::GraceWithEvent, ::nfsService::GraceStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nfsService::GraceWithEvent, ::nfsService::GraceStatus>* streamer) {
                       return this->StreamedStartGraceWithEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartGraceWithEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartGraceWithEvent(::grpc::ServerContext* /*context*/, const ::nfsService::GraceWithEvent* /*request*/, ::nfsService::GraceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartGraceWithEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nfsService::GraceWithEvent,::nfsService::GraceStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartGraceWithEvent<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartGraceWithEvent<Service > StreamedService;
};

// Get session ids 
class GetSessionId final {
 public:
  static constexpr char const* service_full_name() {
    return "nfsService.GetSessionId";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::nfsService::GetSessionIdsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>> AsyncGetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>>(AsyncGetSessionIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>> PrepareAsyncGetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>>(PrepareAsyncGetSessionIdsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>* AsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nfsService::GetSessionIdsResponse>* PrepareAsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::nfsService::GetSessionIdsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>> AsyncGetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>>(AsyncGetSessionIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>> PrepareAsyncGetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>>(PrepareAsyncGetSessionIdsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>* AsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>* PrepareAsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSessionIds_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSessionIds(::grpc::ServerContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSessionIds(::grpc::ServerContext* context, ::nfsService::GetSessionIdsRequest* request, ::grpc::ServerAsyncResponseWriter< ::nfsService::GetSessionIdsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSessionIds<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response) { return this->GetSessionIds(context, request, response); }));}
    void SetMessageAllocatorFor_GetSessionIds(
        ::grpc::MessageAllocator< ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSessionIds(
      ::grpc::CallbackServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetSessionIds<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSessionIds(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSessionIds(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSessionIds(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSessionIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSessionIds() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse>* streamer) {
                       return this->StreamedGetSessionIds(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSessionIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSessionIds(::grpc::ServerContext* /*context*/, const ::nfsService::GetSessionIdsRequest* /*request*/, ::nfsService::GetSessionIdsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSessionIds(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nfsService::GetSessionIdsRequest,::nfsService::GetSessionIdsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSessionIds<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSessionIds<Service > StreamedService;
};

}  // namespace nfsService


#endif  // GRPC_nfsService_2eproto__INCLUDED
