// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfsService.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_nfsService_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_nfsService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_nfsService_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_nfsService_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nfsService_2eproto;
namespace nfsService {
class GetClientIdsRequest;
class GetClientIdsRequestDefaultTypeInternal;
extern GetClientIdsRequestDefaultTypeInternal _GetClientIdsRequest_default_instance_;
class GetClientIdsResponse;
class GetClientIdsResponseDefaultTypeInternal;
extern GetClientIdsResponseDefaultTypeInternal _GetClientIdsResponse_default_instance_;
class GetNfsGraceRequest;
class GetNfsGraceRequestDefaultTypeInternal;
extern GetNfsGraceRequestDefaultTypeInternal _GetNfsGraceRequest_default_instance_;
class GetNfsGraceResponse;
class GetNfsGraceResponseDefaultTypeInternal;
extern GetNfsGraceResponseDefaultTypeInternal _GetNfsGraceResponse_default_instance_;
class GetSessionIdsRequest;
class GetSessionIdsRequestDefaultTypeInternal;
extern GetSessionIdsRequestDefaultTypeInternal _GetSessionIdsRequest_default_instance_;
class GetSessionIdsResponse;
class GetSessionIdsResponseDefaultTypeInternal;
extern GetSessionIdsResponseDefaultTypeInternal _GetSessionIdsResponse_default_instance_;
class GraceStatus;
class GraceStatusDefaultTypeInternal;
extern GraceStatusDefaultTypeInternal _GraceStatus_default_instance_;
class GraceWithEvent;
class GraceWithEventDefaultTypeInternal;
extern GraceWithEventDefaultTypeInternal _GraceWithEvent_default_instance_;
}  // namespace nfsService
PROTOBUF_NAMESPACE_OPEN
template<> ::nfsService::GetClientIdsRequest* Arena::CreateMaybeMessage<::nfsService::GetClientIdsRequest>(Arena*);
template<> ::nfsService::GetClientIdsResponse* Arena::CreateMaybeMessage<::nfsService::GetClientIdsResponse>(Arena*);
template<> ::nfsService::GetNfsGraceRequest* Arena::CreateMaybeMessage<::nfsService::GetNfsGraceRequest>(Arena*);
template<> ::nfsService::GetNfsGraceResponse* Arena::CreateMaybeMessage<::nfsService::GetNfsGraceResponse>(Arena*);
template<> ::nfsService::GetSessionIdsRequest* Arena::CreateMaybeMessage<::nfsService::GetSessionIdsRequest>(Arena*);
template<> ::nfsService::GetSessionIdsResponse* Arena::CreateMaybeMessage<::nfsService::GetSessionIdsResponse>(Arena*);
template<> ::nfsService::GraceStatus* Arena::CreateMaybeMessage<::nfsService::GraceStatus>(Arena*);
template<> ::nfsService::GraceWithEvent* Arena::CreateMaybeMessage<::nfsService::GraceWithEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nfsService {

// ===================================================================

class GetClientIdsRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetClientIdsRequest) */ {
 public:
  inline GetClientIdsRequest() : GetClientIdsRequest(nullptr) {}
  virtual ~GetClientIdsRequest();

  GetClientIdsRequest(const GetClientIdsRequest& from);
  GetClientIdsRequest(GetClientIdsRequest&& from) noexcept
    : GetClientIdsRequest() {
    *this = ::std::move(from);
  }

  inline GetClientIdsRequest& operator=(const GetClientIdsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetClientIdsRequest& operator=(GetClientIdsRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetClientIdsRequest& default_instance();

  static inline const GetClientIdsRequest* internal_default_instance() {
    return reinterpret_cast<const GetClientIdsRequest*>(
               &_GetClientIdsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetClientIdsRequest& a, GetClientIdsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetClientIdsRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetClientIdsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetClientIdsRequest* New() const final {
    return CreateMaybeMessage<GetClientIdsRequest>(nullptr);
  }

  GetClientIdsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetClientIdsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetClientIdsRequest& from);
  void MergeFrom(const GetClientIdsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetClientIdsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetClientIdsRequest";
  }
  protected:
  explicit GetClientIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nfsService.GetClientIdsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GetClientIdsResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetClientIdsResponse) */ {
 public:
  inline GetClientIdsResponse() : GetClientIdsResponse(nullptr) {}
  virtual ~GetClientIdsResponse();

  GetClientIdsResponse(const GetClientIdsResponse& from);
  GetClientIdsResponse(GetClientIdsResponse&& from) noexcept
    : GetClientIdsResponse() {
    *this = ::std::move(from);
  }

  inline GetClientIdsResponse& operator=(const GetClientIdsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetClientIdsResponse& operator=(GetClientIdsResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetClientIdsResponse& default_instance();

  static inline const GetClientIdsResponse* internal_default_instance() {
    return reinterpret_cast<const GetClientIdsResponse*>(
               &_GetClientIdsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetClientIdsResponse& a, GetClientIdsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetClientIdsResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetClientIdsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetClientIdsResponse* New() const final {
    return CreateMaybeMessage<GetClientIdsResponse>(nullptr);
  }

  GetClientIdsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetClientIdsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetClientIdsResponse& from);
  void MergeFrom(const GetClientIdsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetClientIdsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetClientIdsResponse";
  }
  protected:
  explicit GetClientIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdsFieldNumber = 1,
  };
  // repeated uint64 client_ids = 1;
  int client_ids_size() const;
  private:
  int _internal_client_ids_size() const;
  public:
  void clear_client_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_client_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_client_ids() const;
  void _internal_add_client_ids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_client_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 client_ids(int index) const;
  void set_client_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_client_ids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      client_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_client_ids();

  // @@protoc_insertion_point(class_scope:nfsService.GetClientIdsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > client_ids_;
  mutable std::atomic<int> _client_ids_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GetNfsGraceRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetNfsGraceRequest) */ {
 public:
  inline GetNfsGraceRequest() : GetNfsGraceRequest(nullptr) {}
  virtual ~GetNfsGraceRequest();

  GetNfsGraceRequest(const GetNfsGraceRequest& from);
  GetNfsGraceRequest(GetNfsGraceRequest&& from) noexcept
    : GetNfsGraceRequest() {
    *this = ::std::move(from);
  }

  inline GetNfsGraceRequest& operator=(const GetNfsGraceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetNfsGraceRequest& operator=(GetNfsGraceRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetNfsGraceRequest& default_instance();

  static inline const GetNfsGraceRequest* internal_default_instance() {
    return reinterpret_cast<const GetNfsGraceRequest*>(
               &_GetNfsGraceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetNfsGraceRequest& a, GetNfsGraceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetNfsGraceRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetNfsGraceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetNfsGraceRequest* New() const final {
    return CreateMaybeMessage<GetNfsGraceRequest>(nullptr);
  }

  GetNfsGraceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetNfsGraceRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetNfsGraceRequest& from);
  void MergeFrom(const GetNfsGraceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetNfsGraceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetNfsGraceRequest";
  }
  protected:
  explicit GetNfsGraceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nfsService.GetNfsGraceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GetNfsGraceResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetNfsGraceResponse) */ {
 public:
  inline GetNfsGraceResponse() : GetNfsGraceResponse(nullptr) {}
  virtual ~GetNfsGraceResponse();

  GetNfsGraceResponse(const GetNfsGraceResponse& from);
  GetNfsGraceResponse(GetNfsGraceResponse&& from) noexcept
    : GetNfsGraceResponse() {
    *this = ::std::move(from);
  }

  inline GetNfsGraceResponse& operator=(const GetNfsGraceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetNfsGraceResponse& operator=(GetNfsGraceResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetNfsGraceResponse& default_instance();

  static inline const GetNfsGraceResponse* internal_default_instance() {
    return reinterpret_cast<const GetNfsGraceResponse*>(
               &_GetNfsGraceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetNfsGraceResponse& a, GetNfsGraceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetNfsGraceResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetNfsGraceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetNfsGraceResponse* New() const final {
    return CreateMaybeMessage<GetNfsGraceResponse>(nullptr);
  }

  GetNfsGraceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetNfsGraceResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetNfsGraceResponse& from);
  void MergeFrom(const GetNfsGraceResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetNfsGraceResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetNfsGraceResponse";
  }
  protected:
  explicit GetNfsGraceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIngraceFieldNumber = 1,
  };
  // bool ingrace = 1;
  bool has_ingrace() const;
  private:
  bool _internal_has_ingrace() const;
  public:
  void clear_ingrace();
  bool ingrace() const;
  void set_ingrace(bool value);
  private:
  bool _internal_ingrace() const;
  void _internal_set_ingrace(bool value);
  public:

  // @@protoc_insertion_point(class_scope:nfsService.GetNfsGraceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool ingrace_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GraceWithEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GraceWithEvent) */ {
 public:
  inline GraceWithEvent() : GraceWithEvent(nullptr) {}
  virtual ~GraceWithEvent();

  GraceWithEvent(const GraceWithEvent& from);
  GraceWithEvent(GraceWithEvent&& from) noexcept
    : GraceWithEvent() {
    *this = ::std::move(from);
  }

  inline GraceWithEvent& operator=(const GraceWithEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraceWithEvent& operator=(GraceWithEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraceWithEvent& default_instance();

  static inline const GraceWithEvent* internal_default_instance() {
    return reinterpret_cast<const GraceWithEvent*>(
               &_GraceWithEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GraceWithEvent& a, GraceWithEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(GraceWithEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraceWithEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraceWithEvent* New() const final {
    return CreateMaybeMessage<GraceWithEvent>(nullptr);
  }

  GraceWithEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraceWithEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraceWithEvent& from);
  void MergeFrom(const GraceWithEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraceWithEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GraceWithEvent";
  }
  protected:
  explicit GraceWithEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpAddrFieldNumber = 3,
    kEventFieldNumber = 1,
    kNodeIdFieldNumber = 2,
  };
  // string IpAddr = 3;
  void clear_ipaddr();
  const std::string& ipaddr() const;
  void set_ipaddr(const std::string& value);
  void set_ipaddr(std::string&& value);
  void set_ipaddr(const char* value);
  void set_ipaddr(const char* value, size_t size);
  std::string* mutable_ipaddr();
  std::string* release_ipaddr();
  void set_allocated_ipaddr(std::string* ipaddr);
  private:
  const std::string& _internal_ipaddr() const;
  void _internal_set_ipaddr(const std::string& value);
  std::string* _internal_mutable_ipaddr();
  public:

  // int32 Event = 1;
  void clear_event();
  ::PROTOBUF_NAMESPACE_ID::int32 event() const;
  void set_event(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_event() const;
  void _internal_set_event(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 NodeId = 2;
  void clear_nodeid();
  ::PROTOBUF_NAMESPACE_ID::int32 nodeid() const;
  void set_nodeid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nodeid() const;
  void _internal_set_nodeid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:nfsService.GraceWithEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ipaddr_;
  ::PROTOBUF_NAMESPACE_ID::int32 event_;
  ::PROTOBUF_NAMESPACE_ID::int32 nodeid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GraceStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GraceStatus) */ {
 public:
  inline GraceStatus() : GraceStatus(nullptr) {}
  virtual ~GraceStatus();

  GraceStatus(const GraceStatus& from);
  GraceStatus(GraceStatus&& from) noexcept
    : GraceStatus() {
    *this = ::std::move(from);
  }

  inline GraceStatus& operator=(const GraceStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraceStatus& operator=(GraceStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraceStatus& default_instance();

  static inline const GraceStatus* internal_default_instance() {
    return reinterpret_cast<const GraceStatus*>(
               &_GraceStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GraceStatus& a, GraceStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(GraceStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraceStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraceStatus* New() const final {
    return CreateMaybeMessage<GraceStatus>(nullptr);
  }

  GraceStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraceStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraceStatus& from);
  void MergeFrom(const GraceStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraceStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GraceStatus";
  }
  protected:
  explicit GraceStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseMsgFieldNumber = 2,
    kGraceStartedFieldNumber = 1,
  };
  // string response_msg = 2;
  void clear_response_msg();
  const std::string& response_msg() const;
  void set_response_msg(const std::string& value);
  void set_response_msg(std::string&& value);
  void set_response_msg(const char* value);
  void set_response_msg(const char* value, size_t size);
  std::string* mutable_response_msg();
  std::string* release_response_msg();
  void set_allocated_response_msg(std::string* response_msg);
  private:
  const std::string& _internal_response_msg() const;
  void _internal_set_response_msg(const std::string& value);
  std::string* _internal_mutable_response_msg();
  public:

  // bool graceStarted = 1;
  void clear_gracestarted();
  bool gracestarted() const;
  void set_gracestarted(bool value);
  private:
  bool _internal_gracestarted() const;
  void _internal_set_gracestarted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:nfsService.GraceStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_msg_;
  bool gracestarted_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GetSessionIdsRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetSessionIdsRequest) */ {
 public:
  inline GetSessionIdsRequest() : GetSessionIdsRequest(nullptr) {}
  virtual ~GetSessionIdsRequest();

  GetSessionIdsRequest(const GetSessionIdsRequest& from);
  GetSessionIdsRequest(GetSessionIdsRequest&& from) noexcept
    : GetSessionIdsRequest() {
    *this = ::std::move(from);
  }

  inline GetSessionIdsRequest& operator=(const GetSessionIdsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetSessionIdsRequest& operator=(GetSessionIdsRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetSessionIdsRequest& default_instance();

  static inline const GetSessionIdsRequest* internal_default_instance() {
    return reinterpret_cast<const GetSessionIdsRequest*>(
               &_GetSessionIdsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetSessionIdsRequest& a, GetSessionIdsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetSessionIdsRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetSessionIdsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetSessionIdsRequest* New() const final {
    return CreateMaybeMessage<GetSessionIdsRequest>(nullptr);
  }

  GetSessionIdsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetSessionIdsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetSessionIdsRequest& from);
  void MergeFrom(const GetSessionIdsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetSessionIdsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetSessionIdsRequest";
  }
  protected:
  explicit GetSessionIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:nfsService.GetSessionIdsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// -------------------------------------------------------------------

class GetSessionIdsResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nfsService.GetSessionIdsResponse) */ {
 public:
  inline GetSessionIdsResponse() : GetSessionIdsResponse(nullptr) {}
  virtual ~GetSessionIdsResponse();

  GetSessionIdsResponse(const GetSessionIdsResponse& from);
  GetSessionIdsResponse(GetSessionIdsResponse&& from) noexcept
    : GetSessionIdsResponse() {
    *this = ::std::move(from);
  }

  inline GetSessionIdsResponse& operator=(const GetSessionIdsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetSessionIdsResponse& operator=(GetSessionIdsResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetSessionIdsResponse& default_instance();

  static inline const GetSessionIdsResponse* internal_default_instance() {
    return reinterpret_cast<const GetSessionIdsResponse*>(
               &_GetSessionIdsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetSessionIdsResponse& a, GetSessionIdsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetSessionIdsResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetSessionIdsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetSessionIdsResponse* New() const final {
    return CreateMaybeMessage<GetSessionIdsResponse>(nullptr);
  }

  GetSessionIdsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetSessionIdsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetSessionIdsResponse& from);
  void MergeFrom(const GetSessionIdsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetSessionIdsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nfsService.GetSessionIdsResponse";
  }
  protected:
  explicit GetSessionIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nfsService_2eproto);
    return ::descriptor_table_nfsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdsFieldNumber = 1,
  };
  // repeated string session_ids = 1;
  int session_ids_size() const;
  private:
  int _internal_session_ids_size() const;
  public:
  void clear_session_ids();
  const std::string& session_ids(int index) const;
  std::string* mutable_session_ids(int index);
  void set_session_ids(int index, const std::string& value);
  void set_session_ids(int index, std::string&& value);
  void set_session_ids(int index, const char* value);
  void set_session_ids(int index, const char* value, size_t size);
  std::string* add_session_ids();
  void add_session_ids(const std::string& value);
  void add_session_ids(std::string&& value);
  void add_session_ids(const char* value);
  void add_session_ids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& session_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_session_ids();
  private:
  const std::string& _internal_session_ids(int index) const;
  std::string* _internal_add_session_ids();
  public:

  // @@protoc_insertion_point(class_scope:nfsService.GetSessionIdsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> session_ids_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_nfsService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetClientIdsRequest

// -------------------------------------------------------------------

// GetClientIdsResponse

// repeated uint64 client_ids = 1;
inline int GetClientIdsResponse::_internal_client_ids_size() const {
  return client_ids_.size();
}
inline int GetClientIdsResponse::client_ids_size() const {
  return _internal_client_ids_size();
}
inline void GetClientIdsResponse::clear_client_ids() {
  client_ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetClientIdsResponse::_internal_client_ids(int index) const {
  return client_ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetClientIdsResponse::client_ids(int index) const {
  // @@protoc_insertion_point(field_get:nfsService.GetClientIdsResponse.client_ids)
  return _internal_client_ids(index);
}
inline void GetClientIdsResponse::set_client_ids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  client_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:nfsService.GetClientIdsResponse.client_ids)
}
inline void GetClientIdsResponse::_internal_add_client_ids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  client_ids_.Add(value);
}
inline void GetClientIdsResponse::add_client_ids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_client_ids(value);
  // @@protoc_insertion_point(field_add:nfsService.GetClientIdsResponse.client_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
GetClientIdsResponse::_internal_client_ids() const {
  return client_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
GetClientIdsResponse::client_ids() const {
  // @@protoc_insertion_point(field_list:nfsService.GetClientIdsResponse.client_ids)
  return _internal_client_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
GetClientIdsResponse::_internal_mutable_client_ids() {
  return &client_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
GetClientIdsResponse::mutable_client_ids() {
  // @@protoc_insertion_point(field_mutable_list:nfsService.GetClientIdsResponse.client_ids)
  return _internal_mutable_client_ids();
}

// -------------------------------------------------------------------

// GetNfsGraceRequest

// -------------------------------------------------------------------

// GetNfsGraceResponse

// bool ingrace = 1;
inline bool GetNfsGraceResponse::_internal_has_ingrace() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GetNfsGraceResponse::has_ingrace() const {
  return _internal_has_ingrace();
}
inline void GetNfsGraceResponse::clear_ingrace() {
  ingrace_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool GetNfsGraceResponse::_internal_ingrace() const {
  return ingrace_;
}
inline bool GetNfsGraceResponse::ingrace() const {
  // @@protoc_insertion_point(field_get:nfsService.GetNfsGraceResponse.ingrace)
  return _internal_ingrace();
}
inline void GetNfsGraceResponse::_internal_set_ingrace(bool value) {
  _has_bits_[0] |= 0x00000001u;
  ingrace_ = value;
}
inline void GetNfsGraceResponse::set_ingrace(bool value) {
  _internal_set_ingrace(value);
  // @@protoc_insertion_point(field_set:nfsService.GetNfsGraceResponse.ingrace)
}

// -------------------------------------------------------------------

// GraceWithEvent

// int32 Event = 1;
inline void GraceWithEvent::clear_event() {
  event_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GraceWithEvent::_internal_event() const {
  return event_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GraceWithEvent::event() const {
  // @@protoc_insertion_point(field_get:nfsService.GraceWithEvent.Event)
  return _internal_event();
}
inline void GraceWithEvent::_internal_set_event(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  event_ = value;
}
inline void GraceWithEvent::set_event(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_event(value);
  // @@protoc_insertion_point(field_set:nfsService.GraceWithEvent.Event)
}

// int32 NodeId = 2;
inline void GraceWithEvent::clear_nodeid() {
  nodeid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GraceWithEvent::_internal_nodeid() const {
  return nodeid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GraceWithEvent::nodeid() const {
  // @@protoc_insertion_point(field_get:nfsService.GraceWithEvent.NodeId)
  return _internal_nodeid();
}
inline void GraceWithEvent::_internal_set_nodeid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nodeid_ = value;
}
inline void GraceWithEvent::set_nodeid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:nfsService.GraceWithEvent.NodeId)
}

// string IpAddr = 3;
inline void GraceWithEvent::clear_ipaddr() {
  ipaddr_.ClearToEmpty();
}
inline const std::string& GraceWithEvent::ipaddr() const {
  // @@protoc_insertion_point(field_get:nfsService.GraceWithEvent.IpAddr)
  return _internal_ipaddr();
}
inline void GraceWithEvent::set_ipaddr(const std::string& value) {
  _internal_set_ipaddr(value);
  // @@protoc_insertion_point(field_set:nfsService.GraceWithEvent.IpAddr)
}
inline std::string* GraceWithEvent::mutable_ipaddr() {
  // @@protoc_insertion_point(field_mutable:nfsService.GraceWithEvent.IpAddr)
  return _internal_mutable_ipaddr();
}
inline const std::string& GraceWithEvent::_internal_ipaddr() const {
  return ipaddr_.Get();
}
inline void GraceWithEvent::_internal_set_ipaddr(const std::string& value) {
  
  ipaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GraceWithEvent::set_ipaddr(std::string&& value) {
  
  ipaddr_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:nfsService.GraceWithEvent.IpAddr)
}
inline void GraceWithEvent::set_ipaddr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ipaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:nfsService.GraceWithEvent.IpAddr)
}
inline void GraceWithEvent::set_ipaddr(const char* value,
    size_t size) {
  
  ipaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:nfsService.GraceWithEvent.IpAddr)
}
inline std::string* GraceWithEvent::_internal_mutable_ipaddr() {
  
  return ipaddr_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GraceWithEvent::release_ipaddr() {
  // @@protoc_insertion_point(field_release:nfsService.GraceWithEvent.IpAddr)
  return ipaddr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraceWithEvent::set_allocated_ipaddr(std::string* ipaddr) {
  if (ipaddr != nullptr) {
    
  } else {
    
  }
  ipaddr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ipaddr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:nfsService.GraceWithEvent.IpAddr)
}

// -------------------------------------------------------------------

// GraceStatus

// bool graceStarted = 1;
inline void GraceStatus::clear_gracestarted() {
  gracestarted_ = false;
}
inline bool GraceStatus::_internal_gracestarted() const {
  return gracestarted_;
}
inline bool GraceStatus::gracestarted() const {
  // @@protoc_insertion_point(field_get:nfsService.GraceStatus.graceStarted)
  return _internal_gracestarted();
}
inline void GraceStatus::_internal_set_gracestarted(bool value) {
  
  gracestarted_ = value;
}
inline void GraceStatus::set_gracestarted(bool value) {
  _internal_set_gracestarted(value);
  // @@protoc_insertion_point(field_set:nfsService.GraceStatus.graceStarted)
}

// string response_msg = 2;
inline void GraceStatus::clear_response_msg() {
  response_msg_.ClearToEmpty();
}
inline const std::string& GraceStatus::response_msg() const {
  // @@protoc_insertion_point(field_get:nfsService.GraceStatus.response_msg)
  return _internal_response_msg();
}
inline void GraceStatus::set_response_msg(const std::string& value) {
  _internal_set_response_msg(value);
  // @@protoc_insertion_point(field_set:nfsService.GraceStatus.response_msg)
}
inline std::string* GraceStatus::mutable_response_msg() {
  // @@protoc_insertion_point(field_mutable:nfsService.GraceStatus.response_msg)
  return _internal_mutable_response_msg();
}
inline const std::string& GraceStatus::_internal_response_msg() const {
  return response_msg_.Get();
}
inline void GraceStatus::_internal_set_response_msg(const std::string& value) {
  
  response_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GraceStatus::set_response_msg(std::string&& value) {
  
  response_msg_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:nfsService.GraceStatus.response_msg)
}
inline void GraceStatus::set_response_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  response_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:nfsService.GraceStatus.response_msg)
}
inline void GraceStatus::set_response_msg(const char* value,
    size_t size) {
  
  response_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:nfsService.GraceStatus.response_msg)
}
inline std::string* GraceStatus::_internal_mutable_response_msg() {
  
  return response_msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GraceStatus::release_response_msg() {
  // @@protoc_insertion_point(field_release:nfsService.GraceStatus.response_msg)
  return response_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraceStatus::set_allocated_response_msg(std::string* response_msg) {
  if (response_msg != nullptr) {
    
  } else {
    
  }
  response_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), response_msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:nfsService.GraceStatus.response_msg)
}

// -------------------------------------------------------------------

// GetSessionIdsRequest

// -------------------------------------------------------------------

// GetSessionIdsResponse

// repeated string session_ids = 1;
inline int GetSessionIdsResponse::_internal_session_ids_size() const {
  return session_ids_.size();
}
inline int GetSessionIdsResponse::session_ids_size() const {
  return _internal_session_ids_size();
}
inline void GetSessionIdsResponse::clear_session_ids() {
  session_ids_.Clear();
}
inline std::string* GetSessionIdsResponse::add_session_ids() {
  // @@protoc_insertion_point(field_add_mutable:nfsService.GetSessionIdsResponse.session_ids)
  return _internal_add_session_ids();
}
inline const std::string& GetSessionIdsResponse::_internal_session_ids(int index) const {
  return session_ids_.Get(index);
}
inline const std::string& GetSessionIdsResponse::session_ids(int index) const {
  // @@protoc_insertion_point(field_get:nfsService.GetSessionIdsResponse.session_ids)
  return _internal_session_ids(index);
}
inline std::string* GetSessionIdsResponse::mutable_session_ids(int index) {
  // @@protoc_insertion_point(field_mutable:nfsService.GetSessionIdsResponse.session_ids)
  return session_ids_.Mutable(index);
}
inline void GetSessionIdsResponse::set_session_ids(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:nfsService.GetSessionIdsResponse.session_ids)
  session_ids_.Mutable(index)->assign(value);
}
inline void GetSessionIdsResponse::set_session_ids(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:nfsService.GetSessionIdsResponse.session_ids)
  session_ids_.Mutable(index)->assign(std::move(value));
}
inline void GetSessionIdsResponse::set_session_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  session_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:nfsService.GetSessionIdsResponse.session_ids)
}
inline void GetSessionIdsResponse::set_session_ids(int index, const char* value, size_t size) {
  session_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:nfsService.GetSessionIdsResponse.session_ids)
}
inline std::string* GetSessionIdsResponse::_internal_add_session_ids() {
  return session_ids_.Add();
}
inline void GetSessionIdsResponse::add_session_ids(const std::string& value) {
  session_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:nfsService.GetSessionIdsResponse.session_ids)
}
inline void GetSessionIdsResponse::add_session_ids(std::string&& value) {
  session_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:nfsService.GetSessionIdsResponse.session_ids)
}
inline void GetSessionIdsResponse::add_session_ids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  session_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:nfsService.GetSessionIdsResponse.session_ids)
}
inline void GetSessionIdsResponse::add_session_ids(const char* value, size_t size) {
  session_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:nfsService.GetSessionIdsResponse.session_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetSessionIdsResponse::session_ids() const {
  // @@protoc_insertion_point(field_list:nfsService.GetSessionIdsResponse.session_ids)
  return session_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetSessionIdsResponse::mutable_session_ids() {
  // @@protoc_insertion_point(field_mutable_list:nfsService.GetSessionIdsResponse.session_ids)
  return &session_ids_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace nfsService

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_nfsService_2eproto
