// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nfsService.proto

#include "nfsService.pb.h"
#include "nfsService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace nfsService {

static const char* GetClientId_method_names[] = {
  "/nfsService.GetClientId/GetClientIds",
};

std::unique_ptr< GetClientId::Stub> GetClientId::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GetClientId::Stub> stub(new GetClientId::Stub(channel, options));
  return stub;
}

GetClientId::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetClientIds_(GetClientId_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GetClientId::Stub::GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::nfsService::GetClientIdsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClientIds_, context, request, response);
}

void GetClientId::Stub::async::GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClientIds_, context, request, response, std::move(f));
}

void GetClientId::Stub::async::GetClientIds(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClientIds_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>* GetClientId::Stub::PrepareAsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nfsService::GetClientIdsResponse, ::nfsService::GetClientIdsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClientIds_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetClientIdsResponse>* GetClientId::Stub::AsyncGetClientIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetClientIdsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClientIdsRaw(context, request, cq);
  result->StartCall();
  return result;
}

GetClientId::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GetClientId_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GetClientId::Service, ::nfsService::GetClientIdsRequest, ::nfsService::GetClientIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GetClientId::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nfsService::GetClientIdsRequest* req,
             ::nfsService::GetClientIdsResponse* resp) {
               return service->GetClientIds(ctx, req, resp);
             }, this)));
}

GetClientId::Service::~Service() {
}

::grpc::Status GetClientId::Service::GetClientIds(::grpc::ServerContext* context, const ::nfsService::GetClientIdsRequest* request, ::nfsService::GetClientIdsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* GetNfsGrace_method_names[] = {
  "/nfsService.GetNfsGrace/GetGracePeriod",
};

std::unique_ptr< GetNfsGrace::Stub> GetNfsGrace::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GetNfsGrace::Stub> stub(new GetNfsGrace::Stub(channel, options));
  return stub;
}

GetNfsGrace::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetGracePeriod_(GetNfsGrace_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GetNfsGrace::Stub::GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::nfsService::GetNfsGraceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetGracePeriod_, context, request, response);
}

void GetNfsGrace::Stub::async::GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGracePeriod_, context, request, response, std::move(f));
}

void GetNfsGrace::Stub::async::GetGracePeriod(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGracePeriod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>* GetNfsGrace::Stub::PrepareAsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nfsService::GetNfsGraceResponse, ::nfsService::GetNfsGraceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetGracePeriod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetNfsGraceResponse>* GetNfsGrace::Stub::AsyncGetGracePeriodRaw(::grpc::ClientContext* context, const ::nfsService::GetNfsGraceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetGracePeriodRaw(context, request, cq);
  result->StartCall();
  return result;
}

GetNfsGrace::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GetNfsGrace_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GetNfsGrace::Service, ::nfsService::GetNfsGraceRequest, ::nfsService::GetNfsGraceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GetNfsGrace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nfsService::GetNfsGraceRequest* req,
             ::nfsService::GetNfsGraceResponse* resp) {
               return service->GetGracePeriod(ctx, req, resp);
             }, this)));
}

GetNfsGrace::Service::~Service() {
}

::grpc::Status GetNfsGrace::Service::GetGracePeriod(::grpc::ServerContext* context, const ::nfsService::GetNfsGraceRequest* request, ::nfsService::GetNfsGraceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StartNfsGrace_method_names[] = {
  "/nfsService.StartNfsGrace/StartGraceWithEvent",
};

std::unique_ptr< StartNfsGrace::Stub> StartNfsGrace::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StartNfsGrace::Stub> stub(new StartNfsGrace::Stub(channel, options));
  return stub;
}

StartNfsGrace::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartGraceWithEvent_(StartNfsGrace_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StartNfsGrace::Stub::StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::nfsService::GraceStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nfsService::GraceWithEvent, ::nfsService::GraceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartGraceWithEvent_, context, request, response);
}

void StartNfsGrace::Stub::async::StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nfsService::GraceWithEvent, ::nfsService::GraceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGraceWithEvent_, context, request, response, std::move(f));
}

void StartNfsGrace::Stub::async::StartGraceWithEvent(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGraceWithEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>* StartNfsGrace::Stub::PrepareAsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nfsService::GraceStatus, ::nfsService::GraceWithEvent, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartGraceWithEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GraceStatus>* StartNfsGrace::Stub::AsyncStartGraceWithEventRaw(::grpc::ClientContext* context, const ::nfsService::GraceWithEvent& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartGraceWithEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

StartNfsGrace::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StartNfsGrace_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StartNfsGrace::Service, ::nfsService::GraceWithEvent, ::nfsService::GraceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StartNfsGrace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nfsService::GraceWithEvent* req,
             ::nfsService::GraceStatus* resp) {
               return service->StartGraceWithEvent(ctx, req, resp);
             }, this)));
}

StartNfsGrace::Service::~Service() {
}

::grpc::Status StartNfsGrace::Service::StartGraceWithEvent(::grpc::ServerContext* context, const ::nfsService::GraceWithEvent* request, ::nfsService::GraceStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* GetSessionId_method_names[] = {
  "/nfsService.GetSessionId/GetSessionIds",
};

std::unique_ptr< GetSessionId::Stub> GetSessionId::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GetSessionId::Stub> stub(new GetSessionId::Stub(channel, options));
  return stub;
}

GetSessionId::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetSessionIds_(GetSessionId_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GetSessionId::Stub::GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::nfsService::GetSessionIdsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSessionIds_, context, request, response);
}

void GetSessionId::Stub::async::GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionIds_, context, request, response, std::move(f));
}

void GetSessionId::Stub::async::GetSessionIds(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionIds_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>* GetSessionId::Stub::PrepareAsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nfsService::GetSessionIdsResponse, ::nfsService::GetSessionIdsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSessionIds_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nfsService::GetSessionIdsResponse>* GetSessionId::Stub::AsyncGetSessionIdsRaw(::grpc::ClientContext* context, const ::nfsService::GetSessionIdsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSessionIdsRaw(context, request, cq);
  result->StartCall();
  return result;
}

GetSessionId::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GetSessionId_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GetSessionId::Service, ::nfsService::GetSessionIdsRequest, ::nfsService::GetSessionIdsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GetSessionId::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nfsService::GetSessionIdsRequest* req,
             ::nfsService::GetSessionIdsResponse* resp) {
               return service->GetSessionIds(ctx, req, resp);
             }, this)));
}

GetSessionId::Service::~Service() {
}

::grpc::Status GetSessionId::Service::GetSessionIds(::grpc::ServerContext* context, const ::nfsService::GetSessionIdsRequest* request, ::nfsService::GetSessionIdsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nfsService

