// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfsService.proto

#include "nfsService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace nfsService {
class GetClientIdsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetClientIdsRequest> _instance;
} _GetClientIdsRequest_default_instance_;
class GetClientIdsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetClientIdsResponse> _instance;
} _GetClientIdsResponse_default_instance_;
class GetNfsGraceRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetNfsGraceRequest> _instance;
} _GetNfsGraceRequest_default_instance_;
class GetNfsGraceResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetNfsGraceResponse> _instance;
} _GetNfsGraceResponse_default_instance_;
class GetSessionIdsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetSessionIdsRequest> _instance;
} _GetSessionIdsRequest_default_instance_;
class GetSessionIdsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetSessionIdsResponse> _instance;
} _GetSessionIdsResponse_default_instance_;
}  // namespace nfsService
static void InitDefaultsscc_info_GetClientIdsRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetClientIdsRequest_default_instance_;
    new (ptr) ::nfsService::GetClientIdsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetClientIdsRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetClientIdsRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetClientIdsResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetClientIdsResponse_default_instance_;
    new (ptr) ::nfsService::GetClientIdsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetClientIdsResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetClientIdsResponse_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetNfsGraceRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetNfsGraceRequest_default_instance_;
    new (ptr) ::nfsService::GetNfsGraceRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetNfsGraceRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetNfsGraceRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetNfsGraceResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetNfsGraceResponse_default_instance_;
    new (ptr) ::nfsService::GetNfsGraceResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetNfsGraceResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetNfsGraceResponse_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetSessionIdsRequest_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetSessionIdsRequest_default_instance_;
    new (ptr) ::nfsService::GetSessionIdsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetSessionIdsRequest_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetSessionIdsRequest_nfsService_2eproto}, {}};

static void InitDefaultsscc_info_GetSessionIdsResponse_nfsService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::nfsService::_GetSessionIdsResponse_default_instance_;
    new (ptr) ::nfsService::GetSessionIdsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetSessionIdsResponse_nfsService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetSessionIdsResponse_nfsService_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_nfsService_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_nfsService_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_nfsService_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_nfsService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetClientIdsResponse, client_ids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetNfsGraceResponse, ingrace_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::nfsService::GetSessionIdsResponse, session_ids_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::nfsService::GetClientIdsRequest)},
  { 5, -1, sizeof(::nfsService::GetClientIdsResponse)},
  { 11, -1, sizeof(::nfsService::GetNfsGraceRequest)},
  { 16, -1, sizeof(::nfsService::GetNfsGraceResponse)},
  { 22, -1, sizeof(::nfsService::GetSessionIdsRequest)},
  { 27, -1, sizeof(::nfsService::GetSessionIdsResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetClientIdsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetClientIdsResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetNfsGraceRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetNfsGraceResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetSessionIdsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nfsService::_GetSessionIdsResponse_default_instance_),
};

const char descriptor_table_protodef_nfsService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020nfsService.proto\022\nnfsService\"\025\n\023GetCli"
  "entIdsRequest\"*\n\024GetClientIdsResponse\022\022\n"
  "\nclient_ids\030\001 \003(\004\"\024\n\022GetNfsGraceRequest\""
  "&\n\023GetNfsGraceResponse\022\017\n\007ingrace\030\001 \001(\010\""
  "\026\n\024GetSessionIdsRequest\",\n\025GetSessionIds"
  "Response\022\023\n\013session_ids\030\001 \003(\t2`\n\013GetClie"
  "ntId\022Q\n\014GetClientIds\022\037.nfsService.GetCli"
  "entIdsRequest\032 .nfsService.GetClientIdsR"
  "esponse2`\n\013GetNfsGrace\022Q\n\016GetGracePeriod"
  "\022\036.nfsService.GetNfsGraceRequest\032\037.nfsSe"
  "rvice.GetNfsGraceResponse2d\n\014GetSessionI"
  "d\022T\n\rGetSessionIds\022 .nfsService.GetSessi"
  "onIdsRequest\032!.nfsService.GetSessionIdsR"
  "esponseb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_nfsService_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_nfsService_2eproto_sccs[6] = {
  &scc_info_GetClientIdsRequest_nfsService_2eproto.base,
  &scc_info_GetClientIdsResponse_nfsService_2eproto.base,
  &scc_info_GetNfsGraceRequest_nfsService_2eproto.base,
  &scc_info_GetNfsGraceResponse_nfsService_2eproto.base,
  &scc_info_GetSessionIdsRequest_nfsService_2eproto.base,
  &scc_info_GetSessionIdsResponse_nfsService_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_nfsService_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nfsService_2eproto = {
  false, false, descriptor_table_protodef_nfsService_2eproto, "nfsService.proto", 535,
  &descriptor_table_nfsService_2eproto_once, descriptor_table_nfsService_2eproto_sccs, descriptor_table_nfsService_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_nfsService_2eproto::offsets,
  file_level_metadata_nfsService_2eproto, 6, file_level_enum_descriptors_nfsService_2eproto, file_level_service_descriptors_nfsService_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_nfsService_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_nfsService_2eproto)), true);
namespace nfsService {

// ===================================================================

class GetClientIdsRequest::_Internal {
 public:
};

GetClientIdsRequest::GetClientIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetClientIdsRequest)
}
GetClientIdsRequest::GetClientIdsRequest(const GetClientIdsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetClientIdsRequest)
}

void GetClientIdsRequest::SharedCtor() {
}

GetClientIdsRequest::~GetClientIdsRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetClientIdsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetClientIdsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetClientIdsRequest::ArenaDtor(void* object) {
  GetClientIdsRequest* _this = reinterpret_cast< GetClientIdsRequest* >(object);
  (void)_this;
}
void GetClientIdsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetClientIdsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetClientIdsRequest& GetClientIdsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetClientIdsRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetClientIdsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetClientIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetClientIdsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetClientIdsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetClientIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetClientIdsRequest)
  return target;
}

size_t GetClientIdsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetClientIdsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetClientIdsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetClientIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetClientIdsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetClientIdsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetClientIdsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetClientIdsRequest)
    MergeFrom(*source);
  }
}

void GetClientIdsRequest::MergeFrom(const GetClientIdsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetClientIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetClientIdsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetClientIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetClientIdsRequest::CopyFrom(const GetClientIdsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetClientIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetClientIdsRequest::IsInitialized() const {
  return true;
}

void GetClientIdsRequest::InternalSwap(GetClientIdsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetClientIdsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetClientIdsResponse::_Internal {
 public:
};

GetClientIdsResponse::GetClientIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  client_ids_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetClientIdsResponse)
}
GetClientIdsResponse::GetClientIdsResponse(const GetClientIdsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      client_ids_(from.client_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetClientIdsResponse)
}

void GetClientIdsResponse::SharedCtor() {
}

GetClientIdsResponse::~GetClientIdsResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetClientIdsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetClientIdsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetClientIdsResponse::ArenaDtor(void* object) {
  GetClientIdsResponse* _this = reinterpret_cast< GetClientIdsResponse* >(object);
  (void)_this;
}
void GetClientIdsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetClientIdsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetClientIdsResponse& GetClientIdsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetClientIdsResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetClientIdsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetClientIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  client_ids_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetClientIdsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated uint64 client_ids = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_client_ids(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8) {
          _internal_add_client_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetClientIdsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetClientIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint64 client_ids = 1;
  {
    int byte_size = _client_ids_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          1, _internal_client_ids(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetClientIdsResponse)
  return target;
}

size_t GetClientIdsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetClientIdsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 client_ids = 1;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt64Size(this->client_ids_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _client_ids_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetClientIdsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetClientIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetClientIdsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetClientIdsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetClientIdsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetClientIdsResponse)
    MergeFrom(*source);
  }
}

void GetClientIdsResponse::MergeFrom(const GetClientIdsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetClientIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  client_ids_.MergeFrom(from.client_ids_);
}

void GetClientIdsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetClientIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetClientIdsResponse::CopyFrom(const GetClientIdsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetClientIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetClientIdsResponse::IsInitialized() const {
  return true;
}

void GetClientIdsResponse::InternalSwap(GetClientIdsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  client_ids_.InternalSwap(&other->client_ids_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetClientIdsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetNfsGraceRequest::_Internal {
 public:
};

GetNfsGraceRequest::GetNfsGraceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetNfsGraceRequest)
}
GetNfsGraceRequest::GetNfsGraceRequest(const GetNfsGraceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetNfsGraceRequest)
}

void GetNfsGraceRequest::SharedCtor() {
}

GetNfsGraceRequest::~GetNfsGraceRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetNfsGraceRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetNfsGraceRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetNfsGraceRequest::ArenaDtor(void* object) {
  GetNfsGraceRequest* _this = reinterpret_cast< GetNfsGraceRequest* >(object);
  (void)_this;
}
void GetNfsGraceRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetNfsGraceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetNfsGraceRequest& GetNfsGraceRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetNfsGraceRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetNfsGraceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetNfsGraceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNfsGraceRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetNfsGraceRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetNfsGraceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetNfsGraceRequest)
  return target;
}

size_t GetNfsGraceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetNfsGraceRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetNfsGraceRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetNfsGraceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetNfsGraceRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetNfsGraceRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetNfsGraceRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetNfsGraceRequest)
    MergeFrom(*source);
  }
}

void GetNfsGraceRequest::MergeFrom(const GetNfsGraceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetNfsGraceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetNfsGraceRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetNfsGraceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetNfsGraceRequest::CopyFrom(const GetNfsGraceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetNfsGraceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNfsGraceRequest::IsInitialized() const {
  return true;
}

void GetNfsGraceRequest::InternalSwap(GetNfsGraceRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNfsGraceRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetNfsGraceResponse::_Internal {
 public:
};

GetNfsGraceResponse::GetNfsGraceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetNfsGraceResponse)
}
GetNfsGraceResponse::GetNfsGraceResponse(const GetNfsGraceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ingrace_ = from.ingrace_;
  // @@protoc_insertion_point(copy_constructor:nfsService.GetNfsGraceResponse)
}

void GetNfsGraceResponse::SharedCtor() {
  ingrace_ = false;
}

GetNfsGraceResponse::~GetNfsGraceResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetNfsGraceResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetNfsGraceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetNfsGraceResponse::ArenaDtor(void* object) {
  GetNfsGraceResponse* _this = reinterpret_cast< GetNfsGraceResponse* >(object);
  (void)_this;
}
void GetNfsGraceResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetNfsGraceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetNfsGraceResponse& GetNfsGraceResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetNfsGraceResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetNfsGraceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetNfsGraceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ingrace_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetNfsGraceResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool ingrace = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ingrace_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetNfsGraceResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetNfsGraceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ingrace = 1;
  if (this->ingrace() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_ingrace(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetNfsGraceResponse)
  return target;
}

size_t GetNfsGraceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetNfsGraceResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ingrace = 1;
  if (this->ingrace() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetNfsGraceResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetNfsGraceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetNfsGraceResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetNfsGraceResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetNfsGraceResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetNfsGraceResponse)
    MergeFrom(*source);
  }
}

void GetNfsGraceResponse::MergeFrom(const GetNfsGraceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetNfsGraceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ingrace() != 0) {
    _internal_set_ingrace(from._internal_ingrace());
  }
}

void GetNfsGraceResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetNfsGraceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetNfsGraceResponse::CopyFrom(const GetNfsGraceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetNfsGraceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetNfsGraceResponse::IsInitialized() const {
  return true;
}

void GetNfsGraceResponse::InternalSwap(GetNfsGraceResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(ingrace_, other->ingrace_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetNfsGraceResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetSessionIdsRequest::_Internal {
 public:
};

GetSessionIdsRequest::GetSessionIdsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetSessionIdsRequest)
}
GetSessionIdsRequest::GetSessionIdsRequest(const GetSessionIdsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetSessionIdsRequest)
}

void GetSessionIdsRequest::SharedCtor() {
}

GetSessionIdsRequest::~GetSessionIdsRequest() {
  // @@protoc_insertion_point(destructor:nfsService.GetSessionIdsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetSessionIdsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetSessionIdsRequest::ArenaDtor(void* object) {
  GetSessionIdsRequest* _this = reinterpret_cast< GetSessionIdsRequest* >(object);
  (void)_this;
}
void GetSessionIdsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetSessionIdsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetSessionIdsRequest& GetSessionIdsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetSessionIdsRequest_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetSessionIdsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetSessionIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetSessionIdsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetSessionIdsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetSessionIdsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetSessionIdsRequest)
  return target;
}

size_t GetSessionIdsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetSessionIdsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetSessionIdsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetSessionIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSessionIdsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetSessionIdsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetSessionIdsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetSessionIdsRequest)
    MergeFrom(*source);
  }
}

void GetSessionIdsRequest::MergeFrom(const GetSessionIdsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetSessionIdsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetSessionIdsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetSessionIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSessionIdsRequest::CopyFrom(const GetSessionIdsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetSessionIdsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSessionIdsRequest::IsInitialized() const {
  return true;
}

void GetSessionIdsRequest::InternalSwap(GetSessionIdsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetSessionIdsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetSessionIdsResponse::_Internal {
 public:
};

GetSessionIdsResponse::GetSessionIdsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  session_ids_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:nfsService.GetSessionIdsResponse)
}
GetSessionIdsResponse::GetSessionIdsResponse(const GetSessionIdsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      session_ids_(from.session_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:nfsService.GetSessionIdsResponse)
}

void GetSessionIdsResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GetSessionIdsResponse_nfsService_2eproto.base);
}

GetSessionIdsResponse::~GetSessionIdsResponse() {
  // @@protoc_insertion_point(destructor:nfsService.GetSessionIdsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetSessionIdsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetSessionIdsResponse::ArenaDtor(void* object) {
  GetSessionIdsResponse* _this = reinterpret_cast< GetSessionIdsResponse* >(object);
  (void)_this;
}
void GetSessionIdsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetSessionIdsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetSessionIdsResponse& GetSessionIdsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetSessionIdsResponse_nfsService_2eproto.base);
  return *internal_default_instance();
}


void GetSessionIdsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nfsService.GetSessionIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  session_ids_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetSessionIdsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string session_ids = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_session_ids();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "nfsService.GetSessionIdsResponse.session_ids"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetSessionIdsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nfsService.GetSessionIdsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string session_ids = 1;
  for (int i = 0, n = this->_internal_session_ids_size(); i < n; i++) {
    const auto& s = this->_internal_session_ids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "nfsService.GetSessionIdsResponse.session_ids");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nfsService.GetSessionIdsResponse)
  return target;
}

size_t GetSessionIdsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nfsService.GetSessionIdsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string session_ids = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(session_ids_.size());
  for (int i = 0, n = session_ids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      session_ids_.Get(i));
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetSessionIdsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:nfsService.GetSessionIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSessionIdsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetSessionIdsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:nfsService.GetSessionIdsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:nfsService.GetSessionIdsResponse)
    MergeFrom(*source);
  }
}

void GetSessionIdsResponse::MergeFrom(const GetSessionIdsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nfsService.GetSessionIdsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  session_ids_.MergeFrom(from.session_ids_);
}

void GetSessionIdsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:nfsService.GetSessionIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSessionIdsResponse::CopyFrom(const GetSessionIdsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nfsService.GetSessionIdsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSessionIdsResponse::IsInitialized() const {
  return true;
}

void GetSessionIdsResponse::InternalSwap(GetSessionIdsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  session_ids_.InternalSwap(&other->session_ids_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetSessionIdsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace nfsService
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::nfsService::GetClientIdsRequest* Arena::CreateMaybeMessage< ::nfsService::GetClientIdsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetClientIdsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetClientIdsResponse* Arena::CreateMaybeMessage< ::nfsService::GetClientIdsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetClientIdsResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetNfsGraceRequest* Arena::CreateMaybeMessage< ::nfsService::GetNfsGraceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetNfsGraceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetNfsGraceResponse* Arena::CreateMaybeMessage< ::nfsService::GetNfsGraceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetNfsGraceResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetSessionIdsRequest* Arena::CreateMaybeMessage< ::nfsService::GetSessionIdsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetSessionIdsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::nfsService::GetSessionIdsResponse* Arena::CreateMaybeMessage< ::nfsService::GetSessionIdsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nfsService::GetSessionIdsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
