/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs_core.h"
#include "cqos.h"
#include "gsh_rpc.h"

bool xdr_cqos_cmd_type_t (XDR *xdrs, cqos_cmd_type_t *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp))
		return false;
	return true;
}

bool xdr_sockaddr_t(XDR *xdrs, sockaddr_t *objp)
{
	if (!xdr_opaque(xdrs, (char *)objp, sizeof(sockaddr_t)))
		return false;
	return true;
}

bool xdr_cluster_qos_msg (XDR *xdrs, cluster_qos_msg *objp)
{
	if (!xdr_cqos_cmd_type_t (xdrs, &objp->cqos_cmd))
		return false;
	if (!xdr_int32_t (xdrs, &objp->cqos_ops))
		return false;
	if (!xdr_uint16_t (xdrs, &objp->export_id))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->export_rbw))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->export_wbw))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->export_riops))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->export_wiops))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->client_rbw))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->client_wbw))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->client_riops))
		return false;
	if (!xdr_uint64_t (xdrs, &objp->client_wiops))
		return false;
	if (!xdr_sockaddr_t (xdrs, &objp->node_addr))
		return false;
	if (!xdr_sockaddr_t (xdrs, &objp->client_addr))
		return false;
	return true;
}
